services:
    logger:
        class: Psr\Log\NullLogger

    altered_core.mock_http_client:
        class: Symfony\Component\HttpClient\MockHttpClient
        public: true

    App\Client\AlteredCoreClient:
        autowire: true
        arguments:
            $httpClient: '@altered_core.mock_http_client'
            $alteredCoreUrl: '%env(ALTERED_CORE_URL)%'
        tags: ['app.card_data_provider']

    App\Client\RustCardsApiProvider:
        autowire: true
        arguments:
            $httpClient: '@altered_core.mock_http_client'
            $rustCardsApiUrl: '%env(RUST_CARDS_API_URL)%'
        tags: ['app.card_data_provider']

    App\Client\CardDataProviderFactory:
        arguments:
            $providers: !tagged_iterator app.card_data_provider
            $activeProvider: '%env(CARD_DATA_PROVIDER)%'

    altered_draft.mock_http_client:
        class: Symfony\Component\HttpClient\MockHttpClient
        public: true

    App\Client\AlteredDraftSealedPoolClient:
        autowire: true
        arguments:
            $httpClient: '@altered_draft.mock_http_client'
            $alteredDraftUrl: '%env(ALTERED_DRAFT_URL)%'
